#!/usr/bin/env python3
"""Read-only MCP server for Codex QA Memory.

The server intentionally uses only the Python standard library. It reads the
structured QA memory index and the sanitized QA diary generated by this
repository. It never scans raw Codex session JSONL files.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import stat
import sys
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Any, Iterable


SERVER_NAME = "codex-qa-memory-mcp"
SERVER_VERSION = "0.1.0"
LATEST_PROTOCOL_VERSION = "2025-11-25"
SUPPORTED_PROTOCOL_VERSIONS = {
    "2024-11-05",
    "2025-03-26",
    "2025-06-18",
    "2025-11-25",
}

MAX_REQUEST_CHARS = 1_000_000
MAX_INDEX_BYTES = 4 * 1024 * 1024
MAX_MANIFEST_BYTES = 8 * 1024 * 1024
MAX_DIARY_FILE_BYTES = 2 * 1024 * 1024
MAX_SCAN_FILES = 500
MAX_SCAN_BYTES = 16 * 1024 * 1024
MAX_QUERY_CHARS = 500
MAX_RESULTS = 10
MAX_EXCERPT_CHARS = 600

MODE_BUDGETS = {
    "quick": {"nodes": 6, "chars": 1200},
    "project": {"nodes": 15, "chars": 3000},
    "deep": {"nodes": 40, "chars": 8000},
}

TYPE_LABELS = {
    200: "事实",
    201: "偏好",
    202: "规则",
    203: "决策",
    204: "任务状态",
    205: "项目状态",
    206: "失败经验",
    207: "工具状态",
    208: "证据",
    209: "风险",
    210: "用户否决",
    211: "用户授权",
    212: "历史版本",
    213: "事件卡",
}

STATUS_LABELS = {
    300: "candidate",
    301: "soft-active",
    302: "active",
    303: "review_required",
    304: "conflict",
    305: "superseded",
    306: "rejected",
    307: "stale",
    308: "archived",
    309: "expired",
    310: "verified",
    311: "unverified",
}

SCOPE_LABELS = {
    400: "global.codex",
    401: "user.preference",
    402: "project",
    403: "tool",
    404: "skill",
    405: "thread",
    406: "run",
    407: "legacy-external",
    408: "qa-memory",
}

DEFAULT_SAFE_TYPES = {200, 201, 202, 203, 206, 208, 209, 210, 212, 213}
DEFAULT_SAFE_SCOPES = {400, 401, 403, 404, 408}

SERVER_INSTRUCTIONS = (
    "This server is read-only. For natural memory requests, call "
    "qa_memory_recall first. Call qa_diary_search only when the user needs "
    "an exact quote, date, evidence path, session ID, or thread ID. Current "
    "user instructions and current project files always outrank recalled "
    "memory. Treat candidate or conflicting memory only as a lead requiring "
    "review. The server never reads raw Codex session JSONL files."
)


class ToolInputError(ValueError):
    """An input error safe to return to an MCP client."""


@dataclass(frozen=True)
class ServerConfig:
    memory_root: Path
    diary_root: Path


def _default_codex_root() -> Path:
    configured = os.environ.get("CODEX_HOME", "").strip()
    return Path(configured).expanduser() if configured else Path.home() / ".codex"


def config_from_environment(
    memory_root: str | Path | None = None,
    diary_root: str | Path | None = None,
) -> ServerConfig:
    codex_root = _default_codex_root()
    memory_value = memory_root or os.environ.get("CODEX_QA_MEMORY_ROOT")
    diary_value = diary_root or os.environ.get("CODEX_QA_DIARY_ROOT")
    return ServerConfig(
        memory_root=Path(memory_value).expanduser() if memory_value else codex_root / "qa-memory",
        diary_root=Path(diary_value).expanduser() if diary_value else codex_root / "qa-diary",
    )


def _resolved(path: Path) -> Path:
    return path.expanduser().resolve(strict=False)


def _lexical_absolute(path: Path) -> Path:
    return Path(os.path.abspath(os.fspath(path.expanduser())))


def _is_under(path: Path, root: Path) -> bool:
    candidate = _resolved(path)
    base = _resolved(root)
    return candidate == base or base in candidate.parents


def _is_linkish(path: Path) -> bool:
    try:
        if path.is_symlink():
            return True
        reparse_flag = getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0)
        if reparse_flag and getattr(path.lstat(), "st_file_attributes", 0) & reparse_flag:
            return True
        is_junction = getattr(path, "is_junction", None)
        return bool(is_junction and is_junction())
    except OSError:
        return True


def _has_linkish_component(path: Path, root: Path) -> bool:
    candidate = _lexical_absolute(path)
    base = _lexical_absolute(root)
    try:
        relative = candidate.relative_to(base)
    except ValueError:
        return True
    if _is_linkish(base):
        return True
    current = base
    for part in relative.parts:
        current = current / part
        if current.exists() and _is_linkish(current):
            return True
    return not _is_under(candidate, base)


def _safe_child(root: Path, relative: str | Path) -> Path:
    raw = str(relative).strip()
    if not raw or ":" in raw or raw.startswith(("/", "\\")):
        raise ToolInputError("Diary target is not a safe relative path.")
    rel = Path(raw)
    if rel.is_absolute():
        raise ToolInputError("Diary target must be relative to the QA diary root.")
    if any(part == ".." for part in rel.parts):
        raise ToolInputError("Diary target must not contain parent traversal.")
    candidate = _lexical_absolute(root / rel)
    if not _is_under(candidate, root):
        raise ToolInputError("Diary target escapes the QA diary root.")
    if _has_linkish_component(candidate, root):
        raise ToolInputError("Diary target crosses a symbolic link or junction.")
    return candidate


def _read_text(path: Path, root: Path, max_bytes: int) -> str:
    if not _is_under(path, root):
        raise ToolInputError("Requested file is outside the configured QA root.")
    if _has_linkish_component(path, root):
        raise ToolInputError("Symbolic-link or junction files are not read by this server.")
    try:
        size = path.stat().st_size
    except FileNotFoundError as exc:
        raise ToolInputError("Requested QA file does not exist.") from exc
    if size > max_bytes:
        raise ToolInputError("Requested QA file exceeds the safe read limit.")
    return path.read_text(encoding="utf-8", errors="replace")


def _bounded_string(value: Any, field: str, *, required: bool = False) -> str:
    if value is None:
        if required:
            raise ToolInputError(f"{field} is required.")
        return ""
    if not isinstance(value, str):
        raise ToolInputError(f"{field} must be a string.")
    text = value.strip()
    if required and not text:
        raise ToolInputError(f"{field} must not be empty.")
    if len(text) > MAX_QUERY_CHARS:
        raise ToolInputError(f"{field} is too long; maximum is {MAX_QUERY_CHARS} characters.")
    return text


def _bounded_int(value: Any, field: str, minimum: int, maximum: int, default: int) -> int:
    if value is None:
        return default
    if isinstance(value, bool) or not isinstance(value, int):
        raise ToolInputError(f"{field} must be an integer.")
    if value < minimum or value > maximum:
        raise ToolInputError(f"{field} must be between {minimum} and {maximum}.")
    return value


def _redact_output_text(value: Any) -> str:
    text = str(value or "")
    text = re.sub(
        r"-----BEGIN [^-\r\n]*PRIVATE KEY-----.*?-----END [^-\r\n]*PRIVATE KEY-----",
        "[REDACTED_PRIVATE_KEY]",
        text,
        flags=re.IGNORECASE | re.DOTALL,
    )
    text = re.sub(
        r"(?i)\bauthorization\s*[:=]\s*(?:\"[^\"\r\n]*\"|'[^'\r\n]*'|[^\r\n,;]+)",
        "Authorization=[REDACTED]",
        text,
    )
    text = re.sub(
        r"(?i)\b(?:set-cookie|cookie)\s*[:=]\s*(?:\"[^\"\r\n]*\"|'[^'\r\n]*'|[^\r\n]+)",
        "Cookie=[REDACTED]",
        text,
    )
    text = re.sub(r"(?i)\bbearer\s+[A-Za-z0-9._~+/=-]{6,}", "Bearer [REDACTED]", text)
    profile = str(Path.home())
    if profile:
        text = re.sub(re.escape(profile), "%USERPROFILE%", text, flags=re.IGNORECASE)
    text = re.sub(
        r"(?i)([\"'](?:[a-z0-9]+[_-]+)*(?:authorization|api[_ -]?key|access[_ -]?token|refresh[_ -]?token|id[_ -]?token|token|secret(?:[_ -]?access[_ -]?key)?|client[_ -]?secret|cookie|password|passwd|pwd|csrf(?:[_ -]?token)?|xsrf(?:[_ -]?token)?)[\"']\s*:\s*)(?:\"[^\"]*\"|'[^']*'|[^\s,;}]+)",
        lambda match: f"{match.group(1)}\"[REDACTED]\"",
        text,
    )
    text = re.sub(
        r"(?i)\b((?:[a-z0-9]+[_-]+)*(?:authorization|api[_ -]?key|access[_ -]?token|refresh[_ -]?token|id[_ -]?token|token|secret(?:[_ -]?access[_ -]?key)?|client[_ -]?secret|cookie|password|passwd|pwd|csrf(?:[_ -]?token)?|xsrf(?:[_ -]?token)?))\s*[:=]\s*(?:\"[^\"]*\"|'[^']*'|[^\s,;}]+)",
        lambda match: f"{match.group(1)}=[REDACTED]",
        text,
    )
    text = re.sub(
        r"(?i)\b(?:sk|ghp|github_pat|xox[baprs]|npm)[-_][A-Za-z0-9_-]{8,}\b",
        "[REDACTED_TOKEN]",
        text,
    )
    text = re.sub(r"\b(?:AKIA[0-9A-Z]{16}|AIza[0-9A-Za-z_-]{20,})\b", "[REDACTED_TOKEN]", text)
    text = re.sub(
        r"\beyJ[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\b",
        "[REDACTED_JWT]",
        text,
    )
    text = re.sub(r"(?i)\b[A-Z]:[\\/](?:[^\s`'\"<>|]+[\\/]?)+", "<local-path>", text)
    text = re.sub(r"\\\\[^\s`'\"<>|]+\\[^\s`'\"<>|]+", "<local-path>", text)
    return text


def _project_hint_matches(node: dict[str, Any], project_hint: str) -> bool:
    canonical_hint = re.sub(r"[^0-9a-z\u4e00-\u9fff]+", "-", project_hint.casefold()).strip("-")
    if len(canonical_hint) < 3:
        return False
    references = [str(node.get(key, "")).split("#", 1)[0] for key in ("source_ref", "record_path")]
    for reference in references:
        components = [part for part in re.split(r"[/\\]+", reference) if part]
        for index, component in enumerate(components[:-1]):
            if component.casefold() != "projects":
                continue
            project_component = components[index + 1].rsplit(".", 1)[0]
            canonical_project = re.sub(
                r"[^0-9a-z\u4e00-\u9fff]+", "-", project_component.casefold()
            ).strip("-")
            if canonical_project == canonical_hint:
                return True
    return False


def _safe_manifest_id(value: Any) -> str | None:
    text = str(value or "")
    if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._:-]{1,127}", text):
        return None
    return text if _redact_output_text(text) == text else None


def _safe_node_id(value: Any) -> str | None:
    text = str(value or "")
    if not re.fullmatch(r"N-\d{8}-[A-Za-z0-9._-]{1,128}", text):
        return None
    return text if _redact_output_text(text) == text else None


def _safe_anchor(value: Any) -> str | None:
    text = str(value or "")
    if not re.fullmatch(r"[A-Za-z0-9._-]{1,128}", text):
        return None
    return text if _redact_output_text(text) == text else None


def _safe_manifest_time(value: Any) -> str | None:
    text = str(value or "")
    return text if re.fullmatch(r"[0-9TtZz:+.\-]{1,64}", text) else None


def _safe_answer_times(value: Any) -> list[str]:
    if not isinstance(value, list):
        return []
    return [safe for item in value[:64] if (safe := _safe_manifest_time(item)) is not None]


def _fit_node_to_budget(node: dict[str, Any], remaining: int) -> tuple[dict[str, Any] | None, int]:
    candidate = dict(node)

    def serialized_size() -> int:
        return len(json.dumps(candidate, ensure_ascii=False, separators=(",", ":")))

    size = serialized_size()
    if size <= remaining:
        return candidate, size
    candidate["truncated"] = True
    candidate["source_ref"] = str(candidate.get("source_ref", ""))[:160]
    candidate["record_path"] = str(candidate.get("record_path", ""))[:160]
    content = str(candidate.get("content", ""))
    candidate["content"] = content[: max(0, min(len(content), remaining // 2))]
    size = serialized_size()
    while size > remaining and candidate["content"]:
        over = size - remaining
        trim = max(over, max(len(candidate["content"]) // 4, 1))
        candidate["content"] = candidate["content"][:-trim]
        size = serialized_size()
    if size > remaining:
        return None, size
    return candidate, size


def _safe_reference(value: Any, config: ServerConfig) -> str:
    raw = str(value or "").strip()
    if not raw:
        return ""
    normalized = raw.replace("\\", "/")
    for root, label in ((config.diary_root, "qa-diary"), (config.memory_root, "qa-memory")):
        root_text = str(_resolved(root)).replace("\\", "/").rstrip("/")
        if normalized.casefold().startswith(root_text.casefold() + "/"):
            return _redact_output_text(label + normalized[len(root_text) :])[:600]
    if re.match(r"(?i)^[A-Z]:/", normalized) or normalized.startswith(("/", "//")):
        anchor = "#" + normalized.rsplit("#", 1)[1] if "#" in normalized else ""
        filename = normalized.split("#", 1)[0].rstrip("/").rsplit("/", 1)[-1]
        return _redact_output_text(f"<local>/{filename}{anchor}")[:600]
    return _redact_output_text(normalized)[:600]


def _split_markdown_row(line: str) -> list[str]:
    text = line.strip()
    if text.startswith("|"):
        text = text[1:]
    if text.endswith("|") and not text.endswith("\\|"):
        text = text[:-1]
    cells: list[str] = []
    current: list[str] = []
    escaped = False
    for char in text:
        if escaped:
            current.append(char)
            escaped = False
        elif char == "\\":
            escaped = True
        elif char == "|":
            cells.append("".join(current).strip())
            current = []
        else:
            current.append(char)
    if escaped:
        current.append("\\")
    cells.append("".join(current).strip())
    return cells


def _parse_memory_nodes(config: ServerConfig) -> tuple[list[dict[str, Any]], Path]:
    index_path = config.memory_root / "03-索引.md"
    if not index_path.exists():
        raise ToolInputError("QA memory index is not initialized.")
    text = _read_text(index_path, config.memory_root, MAX_INDEX_BYTES)
    nodes: list[dict[str, Any]] = []
    for order, line in enumerate(text.splitlines()):
        if not re.match(r"^\|\s*N-\d{8}-", line):
            continue
        cells = _split_markdown_row(line)
        if len(cells) < 7:
            continue
        node_id = _safe_node_id(cells[0])
        if node_id is None:
            continue
        try:
            type_code = int(cells[1])
            status_code = int(cells[2])
            scope_code = int(cells[3])
        except ValueError:
            continue
        nodes.append(
            {
                "node_id": node_id,
                "type_code": type_code,
                "type_label": TYPE_LABELS.get(type_code, str(type_code)),
                "status_code": status_code,
                "status_label": STATUS_LABELS.get(status_code, str(status_code)),
                "scope_code": scope_code,
                "scope_label": SCOPE_LABELS.get(scope_code, str(scope_code)),
                "content": cells[4],
                "source_ref": cells[5],
                "record_path": cells[6],
                "_order": order,
            }
        )
    return nodes, index_path


def _query_terms(query: str) -> list[str]:
    if not query:
        return []
    parts = re.split(r"[\s,，。！？!?;；:：/\\|()（）\[\]{}]+", query.casefold())
    terms = [part for part in parts if len(part) >= 2]
    if query.casefold() not in terms:
        terms.insert(0, query.casefold())
    return terms[:20]


def _node_score(node: dict[str, Any], query: str, terms: list[str]) -> int:
    if not query:
        return 1
    haystack = " ".join(
        str(node.get(key, "")) for key in ("content", "source_ref", "record_path", "type_label", "scope_label")
    ).casefold()
    score = 0
    full = query.casefold()
    if full in haystack:
        score += 100
    for term in terms:
        if term in haystack:
            score += 10 + min(haystack.count(term), 5)
    return score


def qa_memory_health(config: ServerConfig) -> dict[str, Any]:
    memory_root = _resolved(config.memory_root)
    diary_root = _resolved(config.diary_root)
    index_path = memory_root / "03-索引.md"
    day_names: list[str] = []
    manifest_count = 0
    if diary_root.is_dir():
        for child in diary_root.iterdir():
            if _is_linkish(child) or not child.is_dir() or not re.fullmatch(r"\d{4}-\d{2}-\d{2}", child.name):
                continue
            day_names.append(child.name)
            if (child / "_meta" / "manifest.jsonl").is_file():
                manifest_count += 1
    node_count: int | None = None
    index_error: str | None = None
    index_is_safe_file = index_path.is_file() and not _has_linkish_component(index_path, memory_root)
    if index_is_safe_file:
        try:
            nodes, _ = _parse_memory_nodes(config)
            node_count = len(nodes)
        except ToolInputError as exc:
            index_error = str(exc)
    elif index_path.exists():
        index_error = "QA memory index is not a safe regular file."
    recent_manifest_checks = 0
    recent_manifest_bad_lines = 0
    recent_missing_targets = 0
    recent_missing_anchors = 0
    recent_target_cache: dict[Path, str | None] = {}
    scan_stats = {"files_checked": 0, "bytes_checked": 0}
    health_truncated = False
    health_stop_reason = "exhausted"
    for day_name in sorted(day_names, reverse=True)[:2]:
        if health_truncated:
            break
        day_dir = diary_root / day_name
        manifest = day_dir / "_meta" / "manifest.jsonl"
        if not manifest.is_file() or _has_linkish_component(manifest, diary_root):
            continue
        reserve_error = _reserve_scan_file(manifest, MAX_MANIFEST_BYTES, scan_stats)
        if reserve_error in {"file_budget", "byte_budget"}:
            health_truncated = True
            health_stop_reason = reserve_error
            break
        if reserve_error:
            recent_manifest_bad_lines += 1
            continue
        recent_manifest_checks += 1
        try:
            with manifest.open("r", encoding="utf-8", errors="replace") as handle:
                for line in handle:
                    try:
                        record = json.loads(line)
                    except json.JSONDecodeError:
                        recent_manifest_bad_lines += 1
                        continue
                    if not isinstance(record, dict):
                        recent_manifest_bad_lines += 1
                        continue
                    target_value = record.get("target")
                    anchor = _safe_anchor(record.get("anchor"))
                    if (
                        not isinstance(target_value, str)
                        or not target_value
                        or len(target_value) > 500
                        or anchor is None
                    ):
                        recent_missing_targets += 1
                        continue
                    try:
                        target = _safe_child(day_dir, target_value)
                    except ToolInputError:
                        recent_missing_targets += 1
                        continue
                    if not target.is_file() or _is_linkish(target):
                        recent_missing_targets += 1
                        continue
                    if target not in recent_target_cache:
                        reserve_error = _reserve_scan_file(target, MAX_DIARY_FILE_BYTES, scan_stats)
                        if reserve_error in {"file_budget", "byte_budget"}:
                            health_truncated = True
                            health_stop_reason = reserve_error
                            break
                        if reserve_error:
                            recent_target_cache[target] = None
                            recent_missing_targets += 1
                            continue
                        try:
                            recent_target_cache[target] = _read_text(target, diary_root, MAX_DIARY_FILE_BYTES)
                        except ToolInputError:
                            recent_target_cache[target] = None
                    target_text = recent_target_cache[target]
                    if target_text is None:
                        recent_missing_targets += 1
                        continue
                    if f"{{#{anchor}}}" not in target_text:
                        recent_missing_anchors += 1
        except OSError:
            recent_manifest_bad_lines += 1

    ready = index_is_safe_file and diary_root.is_dir() and index_error is None
    return {
        "schema_version": "1.0",
        "ok": True,
        "ready": ready,
        "read_only": True,
        "memory": {
            "location": "configured QA memory root",
            "exists": memory_root.is_dir(),
            "index_exists": index_is_safe_file,
            "node_count": node_count,
            "error": index_error,
        },
        "diary": {
            "location": "configured QA diary root",
            "exists": diary_root.is_dir(),
            "day_count": len(day_names),
            "latest_day": max(day_names) if day_names else None,
            "manifest_count": manifest_count,
            "recent_manifest_checks": recent_manifest_checks,
            "recent_bad_manifest_lines": recent_manifest_bad_lines,
            "recent_missing_targets": recent_missing_targets,
            "recent_missing_anchors": recent_missing_anchors,
            "scan": scan_stats,
            "scan_truncated": health_truncated,
            "scan_stopped_by": health_stop_reason,
        },
        "write_performed": False,
        "raw_sessions_scanned": False,
    }


def qa_memory_recall(arguments: dict[str, Any], config: ServerConfig) -> dict[str, Any]:
    query = _bounded_string(arguments.get("query"), "query")
    mode = arguments.get("mode", "quick")
    if not isinstance(mode, str) or mode not in MODE_BUDGETS:
        raise ToolInputError("mode must be one of: quick, project, deep.")
    include_candidates = arguments.get("include_candidates", False)
    if not isinstance(include_candidates, bool):
        raise ToolInputError("include_candidates must be a boolean.")
    project_hint = _bounded_string(arguments.get("project_hint"), "project_hint")
    status_codes = {302}
    if include_candidates:
        status_codes.add(300)

    budget = MODE_BUDGETS[mode]
    requested_limit = budget["nodes"]
    nodes, index_path = _parse_memory_nodes(config)
    terms = _query_terms(query)
    ranked: list[tuple[int, int, dict[str, Any]]] = []
    policy_filtered_count = 0
    for node in nodes:
        if node["type_code"] not in DEFAULT_SAFE_TYPES:
            policy_filtered_count += 1
            continue
        if node["scope_code"] not in DEFAULT_SAFE_SCOPES:
            if node["scope_code"] != 402 or not project_hint:
                policy_filtered_count += 1
                continue
            if not _project_hint_matches(node, project_hint):
                policy_filtered_count += 1
                continue
        if node["scope_code"] in {405, 406, 407}:
            policy_filtered_count += 1
            continue
        if status_codes and node["status_code"] not in status_codes:
            continue
        score = _node_score(node, query, terms)
        if query and score <= 0:
            continue
        ranked.append((score, int(node["_order"]), node))
    ranked.sort(key=lambda item: (-item[0], item[1]))

    selected: list[dict[str, Any]] = []
    char_count = 0
    stopped_by = "exhausted"
    for score, _, raw_node in ranked:
        node = {key: value for key, value in raw_node.items() if key != "_order"}
        node["content"] = _redact_output_text(node["content"])
        node["source_ref"] = _safe_reference(node["source_ref"], config)
        node["record_path"] = _safe_reference(node["record_path"], config)
        node["match_score"] = score if query else None
        node["authority"] = "candidate_lead_only" if node["status_code"] == 300 else "recalled_memory"
        if len(selected) >= requested_limit:
            stopped_by = "node_limit"
            break
        remaining = budget["chars"] - char_count
        fitted_node, node_chars = _fit_node_to_budget(node, remaining)
        if fitted_node is None:
            stopped_by = "character_budget"
            break
        selected.append(fitted_node)
        char_count += node_chars

    return {
        "schema_version": "1.0",
        "ok": True,
        "mode": mode,
        "query": _redact_output_text(query)[:MAX_QUERY_CHARS],
        "filters": {
            "status_codes": sorted(status_codes),
            "include_candidates": include_candidates,
            "project_hint": _redact_output_text(project_hint)[:MAX_QUERY_CHARS] if project_hint else None,
            "volatile_types_excluded": True,
            "thread_run_legacy_scopes_excluded": True,
        },
        "budget": {"max_nodes": requested_limit, "max_chars": budget["chars"]},
        "selected_count": len(selected),
        "selected_chars": char_count,
        "nodes": selected,
        "policy_filtered_count": policy_filtered_count,
        "source_refs": [_relative_display(index_path, config.memory_root)],
        "stopped_by": stopped_by,
        "authority_rule": "Current user instructions and current project files outrank recalled memory.",
        "write_performed": False,
    }


def _validate_date(value: Any) -> str:
    text = _bounded_string(value, "date")
    if not text:
        return ""
    if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", text):
        raise ToolInputError("date must use YYYY-MM-DD format.")
    try:
        date.fromisoformat(text)
    except ValueError as exc:
        raise ToolInputError("date is not a valid calendar date.") from exc
    return text


def _validate_session_id(value: Any) -> str:
    text = _bounded_string(value, "session_id")
    if text and not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._:-]{1,127}", text):
        raise ToolInputError("session_id contains unsupported characters.")
    if text and _redact_output_text(text) != text:
        raise ToolInputError("session_id resembles credential material and was rejected.")
    return text


def _validate_source_ref(value: Any) -> str:
    text = _bounded_string(value, "source_ref")
    if not text:
        return ""
    normalized = text.replace("\\", "/")
    if ":" in normalized or normalized.startswith(("/", "//")):
        raise ToolInputError("source_ref must be a relative QA diary reference.")
    if any(part == ".." for part in normalized.split("/")):
        raise ToolInputError("source_ref must not contain parent traversal.")
    return normalized


def _day_directories(root: Path, selected_date: str) -> list[Path]:
    if not root.is_dir():
        return []
    if selected_date:
        candidate = _safe_child(root, selected_date)
        return [candidate] if candidate.is_dir() and not _is_linkish(candidate) else []
    days = [
        child
        for child in root.iterdir()
        if child.is_dir()
        and not _is_linkish(child)
        and re.fullmatch(r"\d{4}-\d{2}-\d{2}", child.name)
    ]
    return sorted(days, key=lambda path: path.name, reverse=True)[:180]


def _manifest_records(path: Path, diary_root: Path) -> Iterable[dict[str, Any]]:
    if not path.is_file() or _has_linkish_component(path, diary_root) or not _is_under(path, diary_root):
        return []
    try:
        if path.stat().st_size > MAX_MANIFEST_BYTES:
            return []
    except OSError:
        return []
    records: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8", errors="replace") as handle:
        for line in handle:
            try:
                item = json.loads(line)
            except json.JSONDecodeError:
                continue
            if isinstance(item, dict):
                records.append(item)
    return records


def _reserve_scan_file(path: Path, per_file_limit: int, stats: dict[str, int]) -> str | None:
    """Reserve one bounded file read and report why it cannot be read."""
    if stats["files_checked"] >= MAX_SCAN_FILES:
        return "file_budget"
    try:
        size = path.stat().st_size
    except OSError:
        return "unreadable"
    if size > per_file_limit:
        return "file_too_large"
    if stats["bytes_checked"] + size > MAX_SCAN_BYTES:
        return "byte_budget"
    stats["files_checked"] += 1
    stats["bytes_checked"] += size
    return None


def _compact_excerpt(text: str, query: str = "") -> str:
    compact = re.sub(r"\s+", " ", _redact_output_text(text)).strip()
    if len(compact) <= MAX_EXCERPT_CHARS:
        return compact
    center = 0
    if query:
        found = compact.casefold().find(query.casefold())
        if found >= 0:
            center = found
    start = max(0, center - MAX_EXCERPT_CHARS // 3)
    end = min(len(compact), start + MAX_EXCERPT_CHARS)
    prefix = "…" if start else ""
    suffix = "…" if end < len(compact) else ""
    return prefix + compact[start:end].strip() + suffix


def _anchor_block(path: Path, anchor: str, diary_root: Path) -> str:
    try:
        text = _read_text(path, diary_root, MAX_DIARY_FILE_BYTES)
    except ToolInputError:
        return ""
    lines = text.splitlines()
    start = next((index for index, line in enumerate(lines) if f"{{#{anchor}}}" in line), None)
    if start is None:
        return ""
    end = len(lines)
    for index in range(start + 1, len(lines)):
        if lines[index].startswith("## Q "):
            end = index
            break
    return "\n".join(lines[start:end])


def _block_around_line(lines: list[str], line_index: int) -> tuple[str | None, str]:
    start = line_index
    while start > 0 and not lines[start].startswith("## Q "):
        start -= 1
    if not lines[start].startswith("## Q "):
        start = max(0, line_index - 2)
    end = line_index + 1
    while end < len(lines) and not lines[end].startswith("## Q "):
        end += 1
    anchor_match = re.search(r"\{#([^}]+)\}", lines[start]) if start < len(lines) else None
    anchor = _safe_anchor(anchor_match.group(1)) if anchor_match else None
    return (anchor, "\n".join(lines[start:end]))


def _relative_display(path: Path, root: Path) -> str:
    try:
        display = str(_resolved(path).relative_to(_resolved(root))).replace("\\", "/")
    except ValueError:
        display = path.name
    return _redact_output_text(display)[:600]


def _session_results(
    days: list[Path],
    diary_root: Path,
    session_id: str,
    query: str,
    limit: int,
) -> tuple[list[dict[str, Any]], dict[str, int], str]:
    results: list[dict[str, Any]] = []
    stats = {"days_checked": 0, "manifests_checked": 0, "files_checked": 0, "bytes_checked": 0}
    stopped_by = "exhausted"
    for day_dir in days:
        if len(results) >= limit:
            stopped_by = "result_limit"
            break
        stats["days_checked"] += 1
        manifest = day_dir / "_meta" / "manifest.jsonl"
        if not manifest.is_file() or _has_linkish_component(manifest, diary_root):
            continue
        reserve_error = _reserve_scan_file(manifest, MAX_MANIFEST_BYTES, stats)
        if reserve_error in {"file_budget", "byte_budget"}:
            stopped_by = reserve_error
            break
        if reserve_error:
            continue
        stats["manifests_checked"] += 1
        for record in _manifest_records(manifest, diary_root):
            session = record.get("session") if isinstance(record.get("session"), dict) else {}
            if str(session.get("id", "")) != session_id:
                continue
            target_value = record.get("target")
            anchor = _safe_anchor(record.get("anchor"))
            if (
                not isinstance(target_value, str)
                or not target_value
                or len(target_value) > 500
                or anchor is None
            ):
                continue
            try:
                target = _safe_child(day_dir, target_value)
            except ToolInputError:
                continue
            if _has_linkish_component(target, diary_root) or not target.is_file() or not _is_under(target, diary_root):
                continue
            reserve_error = _reserve_scan_file(target, MAX_DIARY_FILE_BYTES, stats)
            if reserve_error in {"file_budget", "byte_budget"}:
                stopped_by = reserve_error
                return results, stats, stopped_by
            if reserve_error:
                continue
            block = _anchor_block(target, anchor, diary_root)
            if query and query.casefold() not in block.casefold():
                continue
            results.append(
                {
                    "kind": "session_evidence",
                    "date": day_dir.name,
                    "session_id": session_id,
                    "question_time": _safe_manifest_time(record.get("question_time")),
                    "answer_times": _safe_answer_times(record.get("answer_times")),
                    "path": _relative_display(target, diary_root),
                    "anchor": anchor,
                    "excerpt": _compact_excerpt(block, query),
                }
            )
            if len(results) >= limit:
                stopped_by = "result_limit"
                break
    return results, stats, stopped_by


def _source_ref_results(
    diary_root: Path,
    source_ref: str,
    query: str,
    session_id: str,
) -> tuple[list[dict[str, Any]], dict[str, int], str]:
    stats = {"days_checked": 0, "manifests_checked": 0, "files_checked": 0, "bytes_checked": 0}
    normalized = source_ref
    if normalized.startswith("qa-diary/"):
        normalized = normalized[len("qa-diary/") :]
    path_part, separator, anchor_value = normalized.partition("#")
    anchor = _safe_anchor(anchor_value)
    if not separator or anchor is None:
        raise ToolInputError("source_ref must include a safe #anchor.")
    parts = path_part.split("/", 1)
    if len(parts) != 2:
        raise ToolInputError("source_ref must include date and diary path.")
    selected_date = _validate_date(parts[0])
    day_dir = _safe_child(diary_root, selected_date)
    target = _safe_child(day_dir, parts[1])
    if not day_dir.is_dir() or not target.is_file() or _has_linkish_component(target, diary_root):
        return [], stats, "source_ref_not_found"
    manifest = day_dir / "_meta" / "manifest.jsonl"
    if not manifest.is_file() or _has_linkish_component(manifest, diary_root):
        return [], stats, "source_ref_not_found"
    stats["days_checked"] = 1
    reserve_error = _reserve_scan_file(manifest, MAX_MANIFEST_BYTES, stats)
    if reserve_error:
        return [], stats, reserve_error
    stats["manifests_checked"] = 1
    expected_target = parts[1].replace("\\", "/")
    for record in _manifest_records(manifest, diary_root):
        record_target = str(record.get("target", "")).replace("\\", "/")
        if record_target != expected_target or _safe_anchor(record.get("anchor")) != anchor:
            continue
        session = record.get("session") if isinstance(record.get("session"), dict) else {}
        record_session_id = _safe_manifest_id(session.get("id"))
        if session_id and record_session_id != session_id:
            continue
        reserve_error = _reserve_scan_file(target, MAX_DIARY_FILE_BYTES, stats)
        if reserve_error:
            return [], stats, reserve_error
        block = _anchor_block(target, anchor, diary_root)
        if query and query.casefold() not in block.casefold():
            return [], stats, "source_ref_not_found"
        return [
            {
                "kind": "source_evidence",
                "date": selected_date,
                "session_id": record_session_id,
                "question_time": _safe_manifest_time(record.get("question_time")),
                "answer_times": _safe_answer_times(record.get("answer_times")),
                "path": _relative_display(target, diary_root),
                "anchor": anchor,
                "excerpt": _compact_excerpt(block, query),
            }
        ], stats, "source_ref_resolved"
    return [], stats, "source_ref_not_found"


def _query_results(
    days: list[Path], diary_root: Path, query: str, limit: int
) -> tuple[list[dict[str, Any]], dict[str, int], str]:
    results: list[dict[str, Any]] = []
    stats = {"days_checked": 0, "manifests_checked": 0, "files_checked": 0, "bytes_checked": 0}
    seen: set[tuple[str, str | None]] = set()
    stopped_by = "exhausted"
    for day_dir in days:
        if len(results) >= limit:
            stopped_by = "result_limit"
            break
        stats["days_checked"] += 1
        candidates: list[Path] = []
        for folder_name in ("projects", "general"):
            folder = day_dir / folder_name
            if folder.is_dir() and not _is_linkish(folder):
                candidates.extend(sorted(folder.glob("*.md")))
        index_path = day_dir / "_index.md"
        if index_path.is_file() and not _is_linkish(index_path):
            candidates.append(index_path)
        for path in candidates:
            if len(results) >= limit:
                stopped_by = "result_limit"
                break
            if stats["files_checked"] >= MAX_SCAN_FILES:
                stopped_by = "file_budget"
                return results, stats, stopped_by
            if _has_linkish_component(path, diary_root) or not _is_under(path, diary_root):
                continue
            try:
                size = path.stat().st_size
            except OSError:
                continue
            if size > MAX_DIARY_FILE_BYTES:
                continue
            if stats["bytes_checked"] + size > MAX_SCAN_BYTES:
                stopped_by = "byte_budget"
                return results, stats, stopped_by
            stats["files_checked"] += 1
            stats["bytes_checked"] += size
            text = path.read_text(encoding="utf-8", errors="replace")
            lines = text.splitlines()
            for index, line in enumerate(lines):
                if query.casefold() not in line.casefold():
                    continue
                anchor, block = _block_around_line(lines, index)
                key = (_relative_display(path, diary_root), anchor)
                if key in seen:
                    continue
                seen.add(key)
                results.append(
                    {
                        "kind": "diary_evidence",
                        "date": day_dir.name,
                        "path": key[0],
                        "anchor": anchor,
                        "line": index + 1,
                        "excerpt": _compact_excerpt(block, query),
                    }
                )
                if len(results) >= limit:
                    break
    return results, stats, stopped_by


def _day_index_results(day_dir: Path, diary_root: Path, limit: int) -> list[dict[str, Any]]:
    index_path = day_dir / "_index.md"
    if not index_path.is_file() or _has_linkish_component(index_path, diary_root):
        return []
    text = _read_text(index_path, diary_root, MAX_DIARY_FILE_BYTES)
    results: list[dict[str, Any]] = []
    in_timeline = False
    for line in text.splitlines():
        if line.strip() == "## Script Timeline":
            in_timeline = True
            continue
        if not in_timeline or not line.startswith("|"):
            continue
        cells = _split_markdown_row(line)
        if len(cells) < 4 or cells[0] in {"Time", "---"}:
            continue
        path_value = cells[3].strip("`")
        if len(path_value) > 500:
            continue
        try:
            _safe_child(day_dir, path_value)
        except ToolInputError:
            continue
        results.append(
            {
                "kind": "day_timeline",
                "date": day_dir.name,
                "time": _redact_output_text(cells[0])[:64],
                "scope": _redact_output_text(cells[1])[:80],
                "topic": _redact_output_text(cells[2])[:300],
                "path": _redact_output_text(path_value)[:500],
            }
        )
        if len(results) >= limit:
            break
    return results


def qa_diary_search(arguments: dict[str, Any], config: ServerConfig) -> dict[str, Any]:
    query = _bounded_string(arguments.get("query"), "query")
    selected_date = _validate_date(arguments.get("date"))
    source_ref = _validate_source_ref(arguments.get("source_ref"))
    session_id_value = arguments.get("session_id")
    thread_id_value = arguments.get("thread_id")
    session_id = _validate_session_id(session_id_value)
    thread_id = _validate_session_id(thread_id_value)
    if session_id and thread_id and session_id != thread_id:
        raise ToolInputError("session_id and thread_id must match when both are provided.")
    session_id = session_id or thread_id
    limit = _bounded_int(arguments.get("limit"), "limit", 1, MAX_RESULTS, 8)
    if not any((query, selected_date, session_id, source_ref)):
        raise ToolInputError("Provide at least one of source_ref, query, date, session_id, or thread_id.")

    diary_root = _resolved(config.diary_root)
    days = _day_directories(diary_root, selected_date)
    if source_ref:
        ref_without_prefix = source_ref[len("qa-diary/") :] if source_ref.startswith("qa-diary/") else source_ref
        ref_date = ref_without_prefix.split("/", 1)[0]
        if selected_date and ref_date != selected_date:
            raise ToolInputError("date conflicts with the date encoded in source_ref.")
        results, stats, stopped_by = _source_ref_results(diary_root, source_ref, query, session_id)
        route = "source_ref_manifest"
    elif session_id:
        results, stats, stopped_by = _session_results(days, diary_root, session_id, query, limit)
        route = "manifest"
    elif query:
        results, stats, stopped_by = _query_results(days, diary_root, query, limit)
        route = "diary"
    else:
        results = _day_index_results(days[0], diary_root, limit) if days else []
        index_size = 0
        if days:
            try:
                index_size = min((days[0] / "_index.md").stat().st_size, MAX_DIARY_FILE_BYTES)
            except OSError:
                pass
        stats = {
            "days_checked": 1 if days else 0,
            "manifests_checked": 0,
            "files_checked": 1 if days else 0,
            "bytes_checked": index_size,
        }
        stopped_by = "result_limit" if len(results) >= limit else "exhausted"
        route = "day_index"

    return {
        "schema_version": "1.0",
        "ok": True,
        "query": _redact_output_text(query)[:MAX_QUERY_CHARS],
        "date": selected_date or None,
        "session_id": session_id or None,
        "source_ref": _redact_output_text(source_ref)[:MAX_QUERY_CHARS] if source_ref else None,
        "route": route,
        "result_count": len(results),
        "results": results,
        "scan": stats,
        "stopped_by": stopped_by,
        "raw_sessions_scanned": False,
        "raw_session_fallback": {"supported": False, "used": False},
        "authority_rule": "Diary evidence is a source record; current user instructions and current project files still take priority.",
        "write_performed": False,
    }


READ_ONLY_ANNOTATIONS = {
    "readOnlyHint": True,
    "destructiveHint": False,
    "idempotentHint": True,
    "openWorldHint": False,
}

TOOLS: list[dict[str, Any]] = [
    {
        "name": "qa_memory_health",
        "title": "QA Memory Health",
        "description": "只读检查 Codex QA 结构化记忆与 QA 日记是否已初始化、可读取，以及最近日记日期。不会启动服务或读取原始 session JSONL。",
        "inputSchema": {"type": "object", "properties": {}, "additionalProperties": False},
        "annotations": {"title": "QA Memory Health", **READ_ONLY_ANNOTATIONS},
    },
    {
        "name": "qa_memory_recall",
        "title": "Recall QA Memory",
        "description": "自然回忆的默认入口。按 quick/project/deep 预算只读召回结构化记忆节点；当前指令与当前项目文件始终优先。",
        "inputSchema": {
            "type": "object",
            "properties": {
                "query": {"type": "string", "maxLength": MAX_QUERY_CHARS},
                "mode": {"type": "string", "enum": ["quick", "project", "deep"], "default": "quick"},
                "include_candidates": {"type": "boolean", "default": False},
                "project_hint": {
                    "type": "string",
                    "maxLength": MAX_QUERY_CHARS,
                    "description": "Optional project name or stable project identifier. Project-scoped nodes remain excluded unless this hint matches their stored source path.",
                },
            },
            "additionalProperties": False,
        },
        "annotations": {"title": "Recall QA Memory", **READ_ONLY_ANNOTATIONS},
    },
    {
        "name": "qa_diary_search",
        "title": "Search QA Diary Evidence",
        "description": "仅在需要原话、日期、证据位置或 session/thread ID 时使用。只读查询整理后的 QA 日记和 manifest，不读取原始 session JSONL。",
        "inputSchema": {
            "type": "object",
            "properties": {
                "query": {"type": "string", "maxLength": MAX_QUERY_CHARS},
                "source_ref": {
                    "type": "string",
                    "maxLength": MAX_QUERY_CHARS,
                    "description": "Relative QA diary reference such as qa-diary/YYYY-MM-DD/projects/name.md#anchor.",
                },
                "date": {"type": "string", "description": "YYYY-MM-DD"},
                "session_id": {"type": "string", "maxLength": 128},
                "thread_id": {"type": "string", "maxLength": 128},
                "limit": {"type": "integer", "minimum": 1, "maximum": MAX_RESULTS, "default": 8},
            },
            "additionalProperties": False,
            "anyOf": [
                {"required": ["source_ref"]},
                {"required": ["query"]},
                {"required": ["date"]},
                {"required": ["session_id"]},
                {"required": ["thread_id"]},
            ],
        },
        "annotations": {"title": "Search QA Diary Evidence", **READ_ONLY_ANNOTATIONS},
    },
]


def tool_call(name: str, arguments: dict[str, Any], config: ServerConfig) -> dict[str, Any]:
    allowed = {tool["name"]: set(tool["inputSchema"].get("properties", {})) for tool in TOOLS}
    if name not in allowed:
        raise ToolInputError("Unknown QA MCP tool.")
    unknown = sorted(set(arguments) - allowed[name])
    if unknown:
        raise ToolInputError("Unsupported argument(s) were provided.")
    if name == "qa_memory_health":
        return qa_memory_health(config)
    if name == "qa_memory_recall":
        return qa_memory_recall(arguments, config)
    if name == "qa_diary_search":
        return qa_diary_search(arguments, config)
    raise ToolInputError("Unknown QA MCP tool.")


def _tool_result(data: dict[str, Any], *, is_error: bool = False) -> dict[str, Any]:
    return {
        "content": [{"type": "text", "text": json.dumps(data, ensure_ascii=False, indent=2)}],
        "structuredContent": data,
        "isError": is_error,
    }


def _result(message_id: Any, result: dict[str, Any]) -> dict[str, Any]:
    return {"jsonrpc": "2.0", "id": message_id, "result": result}


def _error(message_id: Any, code: int, message: str) -> dict[str, Any]:
    return {"jsonrpc": "2.0", "id": message_id, "error": {"code": code, "message": message}}


class McpServer:
    def __init__(self, config: ServerConfig):
        self.config = config
        self.initialize_seen = False
        self.initialized = False

    def handle(self, message: Any) -> dict[str, Any] | None:
        if not isinstance(message, dict):
            return _error(None, -32600, "Invalid Request: expected a JSON object.")
        message_id = message.get("id")
        is_notification = "id" not in message
        if message.get("jsonrpc") != "2.0" or not isinstance(message.get("method"), str):
            return None if is_notification else _error(message_id, -32600, "Invalid Request.")
        params = message.get("params", {})
        if not isinstance(params, dict):
            return None if is_notification else _error(message_id, -32602, "Invalid params: expected an object.")

        method = message["method"]
        if method == "initialize":
            if is_notification:
                return None
            requested = params.get("protocolVersion")
            if not isinstance(requested, str):
                return _error(message_id, -32602, "Invalid params: protocolVersion is required.")
            negotiated = requested if requested in SUPPORTED_PROTOCOL_VERSIONS else LATEST_PROTOCOL_VERSION
            self.initialize_seen = True
            return _result(
                message_id,
                {
                    "protocolVersion": negotiated,
                    "capabilities": {"tools": {"listChanged": False}},
                    "serverInfo": {"name": SERVER_NAME, "version": SERVER_VERSION},
                    "instructions": SERVER_INSTRUCTIONS,
                },
            )
        if method == "notifications/initialized":
            if self.initialize_seen:
                self.initialized = True
            return None
        if method in {"notifications/cancelled", "notifications/roots/list_changed"}:
            return None
        if method == "ping":
            return None if is_notification else _result(message_id, {})
        if not self.initialized:
            return None if is_notification else _error(message_id, -32002, "Server not initialized.")
        if method == "tools/list":
            return None if is_notification else _result(message_id, {"tools": TOOLS})
        if method == "tools/call":
            if is_notification:
                return None
            name = params.get("name")
            arguments = params.get("arguments", {})
            if not isinstance(name, str) or not isinstance(arguments, dict):
                return _error(message_id, -32602, "Invalid params for tools/call.")
            try:
                data = tool_call(name, arguments, self.config)
                return _result(message_id, _tool_result(data))
            except ToolInputError as exc:
                return _result(message_id, _tool_result({"ok": False, "error": str(exc)}, is_error=True))
            except Exception:  # Keep private paths and implementation details out of client-visible errors.
                return _result(
                    message_id,
                    _tool_result({"ok": False, "error": "Internal QA MCP tool error."}, is_error=True),
                )
        return None if is_notification else _error(message_id, -32601, "Method not found.")


def _send(message: dict[str, Any]) -> None:
    sys.stdout.write(json.dumps(message, ensure_ascii=False, separators=(",", ":")) + "\n")
    sys.stdout.flush()


def serve_stdio(config: ServerConfig) -> int:
    try:
        sys.stdin.reconfigure(encoding="utf-8")
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")
    except AttributeError:
        pass
    server = McpServer(config)
    while True:
        raw_line = sys.stdin.readline(MAX_REQUEST_CHARS + 1)
        if not raw_line:
            break
        if len(raw_line) > MAX_REQUEST_CHARS:
            while raw_line and not raw_line.endswith("\n"):
                raw_line = sys.stdin.readline(MAX_REQUEST_CHARS + 1)
            _send(_error(None, -32700, "Parse error: request is too large."))
            continue
        line = raw_line.strip()
        if not line:
            continue
        try:
            message = json.loads(line)
        except json.JSONDecodeError:
            _send(_error(None, -32700, "Parse error."))
            continue
        response = server.handle(message)
        if response is not None:
            _send(response)
    return 0


def _emit(data: dict[str, Any]) -> None:
    print(json.dumps(data, ensure_ascii=False, indent=2))


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Read-only Codex QA Memory MCP server")
    parser.add_argument("--version", action="version", version=f"%(prog)s {SERVER_VERSION}")
    parser.add_argument("--memory-root", help="Override QA memory root for this server process.")
    parser.add_argument("--diary-root", help="Override QA diary root for this server process.")
    subparsers = parser.add_subparsers(dest="command")
    subparsers.add_parser("serve", help="Run the stdio MCP server (default).")
    subparsers.add_parser("health", help="Run a one-time read-only health check.")

    recall = subparsers.add_parser("recall", help="Run a one-time structured memory recall.")
    recall.add_argument("--query", default="")
    recall.add_argument("--mode", choices=sorted(MODE_BUDGETS), default="quick")
    recall.add_argument("--include-candidates", action="store_true")
    recall.add_argument("--project-hint", default="")

    diary = subparsers.add_parser("diary-search", help="Run a one-time QA diary evidence search.")
    diary.add_argument("--query", default="")
    diary.add_argument("--source-ref", default="")
    diary.add_argument("--date", default="")
    diary.add_argument("--session-id", default="")
    diary.add_argument("--thread-id", default="")
    diary.add_argument("--limit", type=int, default=8)
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    config = config_from_environment(args.memory_root, args.diary_root)
    if args.command in (None, "serve"):
        return serve_stdio(config)
    try:
        if args.command == "health":
            _emit(qa_memory_health(config))
            return 0
        if args.command == "recall":
            payload: dict[str, Any] = {
                "query": args.query,
                "mode": args.mode,
                "include_candidates": args.include_candidates,
                "project_hint": args.project_hint,
            }
            _emit(qa_memory_recall(payload, config))
            return 0
        if args.command == "diary-search":
            _emit(
                qa_diary_search(
                    {
                        "query": args.query,
                        "source_ref": args.source_ref,
                        "date": args.date,
                        "session_id": args.session_id,
                        "thread_id": args.thread_id,
                        "limit": args.limit,
                    },
                    config,
                )
            )
            return 0
    except ToolInputError as exc:
        _emit({"ok": False, "error": str(exc)})
        return 2
    parser.error("unknown command")
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
